<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class TopicRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
//        dd($this);
        return [
            'name'=>'required|string',
            'thumbnail'=>'required|mimes:jpeg,jpg,png,gif|max:5000',
//            'status'=>'required|string'
        ];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return[
            'name.required'=>'Topic name is required',
            'thumbnail.required'=>'Topic thumbnail is required',
            'thumbnail.mimes'=>'Topic thumbnail is not correct',
            'thumbnail.max'=>'Maximum 5mb thumbnail is allowed',
//            'status.required'=>'status field is required'
        ];
    }
}
